import { resolveMapctxToml } from '@mapctx/store'
import * as path from 'path'

/**
 * R13: after the cutover, the store is the sole authority and the canonical
 * Markdown is regenerated by the mapctx CLI. The legacy `mapcs` sync commands
 * (pull/bootstrap/reconcile/push) are second Markdown writers: their changes
 * are not store events, so the next canonical export overwrites them, and a
 * push can publish stale/drifted Markdown instead of store state. A preserved
 * or recreated legacy config must not resurrect that path silently.
 *
 * Fail closed for post-cutover mutation paths. Reads (status, dry-runs that
 * write nothing) stay allowed.
 */
export type LegacySyncMutation = 'pull' | 'push' | 'bootstrap' | 'reconcile';

export function assertLegacySyncWriterAllowed(operation: LegacySyncMutation, configPath?: string): void {
  const roots = new Set<string>([process.cwd()]);
  if (configPath) roots.add(path.dirname(path.resolve(process.cwd(), configPath)));
  for (const root of roots) {
    const toml = resolveMapctxToml(root);
    if (toml && toml.config.plansAuthority === 'store') {
      throw new Error(
        `legacy sync "${operation}" refused: ${toml.path} declares plansAuthority=store, so the board is generated from the store by the mapctx CLI. ` +
        'Markdown changes made by mapcs would be overwritten by the next canonical export (and push would publish drifted Markdown). ' +
        'Use "mapctx import --commit" to journal explicit imports, and push from store projections once GitHub sync is store-backed.'
      );
    }
  }
}
